name: Alpine
on:
  pull_request:
    paths:
      - '.github/workflows/alpine.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  alpine:
    name: 'Alpine${{ matrix.name }}: depends, no GUI'
    runs-on: ubuntu-latest
    container: alpine:latest
    strategy:
      fail-fast: false
      matrix:
        build-type: [release, debug]
        include:
          - build-type: release
          - build-type: debug
            name: ', debug'
            depends-options: DEBUG=1
            config-options: -DCMAKE_BUILD_TYPE=Debug

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: maflcko/bitcoin-core
          ref: 2602-test-del

      - name: Install dependencies
        run: |
          apk --no-cache --update add bash build-base cmake curl linux-headers make pkgconf python3

      - name: Build depends
        run: |
          gmake -C depends -j $(nproc) ${{ matrix.depends-options }} NO_QT=1 LOG=1

      - name: Generate buildsystem
        run: |
          cmake -B build ${{ matrix.config-options }} \
            --toolchain depends/$(depends/config.sub $(depends/config.guess))/toolchain.cmake \
            -DBUILD_BENCH=ON \
            -DBUILD_FUZZ_BINARY=ON \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Check 'bitcoind' executable
        run: |
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          ldd build/bin/bitcoind
          build/bin/bitcoind -version

      - name: Run test suite
        run: ctest --test-dir build -j $(nproc)

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        run: |
          build/test/functional/test_runner.py -j $(($(nproc) * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix . \
            --extended \
            --timeout-factor=8
