name: Clang-SNAPSHOT
on:
  pull_request:
    paths:
      - '.github/workflows/clang.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  clang:
    name: 'Clang-SNAPSHOT, ${{ matrix.stdlib }}, depends'
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        stdlib: [libstdc++, libc++]
        include:
          - stdlib: libstdc++
          - stdlib: libc++
            dependencies: libc++-${LLVM_VERSION}-dev libc++abi-${LLVM_VERSION}-dev

    steps:
      - name: Checkout Bitcoin Core repo
        id: checkout
        uses: actions/checkout@v7
        with:
          repository: bitcoin/bitcoin

      - name: Install dependencies
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          . /etc/os-release
          REPO_NAME="deb http://apt.llvm.org/${VERSION_CODENAME} llvm-toolchain-${VERSION_CODENAME} main"
          sudo add-apt-repository -y "${REPO_NAME}"
          sudo apt-get update
          LLVM_VERSION=$(apt-cache search --names-only '^clang-[0-9]+$' | sort -V | tail -1 | cut -f1 -d" " | cut -f2 -d"-" )
          echo "LLVM_VERSION=${LLVM_VERSION}" >> "$GITHUB_ENV"
          sudo apt-get install --no-install-recommends clang-${LLVM_VERSION} ${{ matrix.dependencies }}

      - name: Clang version
        run: clang-${LLVM_VERSION} -v 2>&1 | tee clang_version.txt

      - name: Build depends
        run: |
          gmake -C depends -j $(nproc) CC="clang-${LLVM_VERSION}" CXX="clang++-${LLVM_VERSION} -stdlib=${{ matrix.stdlib }}" LOG=1

      - name: Generate CTest configuration
        run: |
          cat << 'EOF' > ctest_config.cmake
          set(CTEST_SITE "${{ github.repository }}")
          set(CTEST_BUILD_NAME "Clang-SNAPSHOT, ${{ matrix.stdlib }}, depends")
          set(CTEST_SOURCE_DIRECTORY "$ENV{GITHUB_WORKSPACE}")
          set(CTEST_BINARY_DIRECTORY "${CTEST_SOURCE_DIRECTORY}/build")
          set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
          cmake_host_system_information(RESULT nproc QUERY NUMBER_OF_LOGICAL_CORES)
          EOF

      - name: CDash -- Start & Update
        shell: ctest --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(${{ case(github.event_name == 'workflow_run', 'Nightly', format('Experimental GROUP {0}', github.event_name)) }})
          set(CTEST_UPDATE_TYPE git)
          # This command may be redundant once the following MR is merged:
          # https://gitlab.kitware.com/cmake/cmake/-/merge_requests/12038
          set(CTEST_UPDATE_COMMAND "${CMAKE_COMMAND} -E true")
          set(CTEST_UPDATE_VERSION_OVERRIDE "${{ steps.checkout.outputs.commit }}")
          ctest_update()

      - name: CDash -- Configure
        shell: ctest --extra-verbose --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          set(configure_opts
            "--preset dev-mode"
            "--toolchain depends/x86_64-pc-linux-gnu/toolchain.cmake"
            "-DCMAKE_COMPILE_WARNING_AS_ERROR=ON"
          )
          ctest_start(APPEND)
          ctest_configure(OPTIONS "${configure_opts}")

      - name: CDash -- Build
        shell: ctest --extra-verbose --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(APPEND)
          ctest_build(PARALLEL_LEVEL ${nproc})

      - name: Check 'bitcoind' executable
        run: |
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          ldd build/bin/bitcoind
          build/bin/bitcoind -version

      - name: Fetch test data
        run: |
          DIR_UNIT_TEST_DATA="$(pwd)/qa-assets/unit_test_data"
          echo "DIR_UNIT_TEST_DATA=${DIR_UNIT_TEST_DATA}" >> "$GITHUB_ENV"
          mkdir -p "$DIR_UNIT_TEST_DATA"
          curl --location --fail --output "${DIR_UNIT_TEST_DATA}/script_assets_test.json" https://github.com/bitcoin-core/qa-assets/raw/main/unit_test_data/script_assets_test.json

      - name: CDash -- Test
        shell: ctest --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(APPEND)
          ctest_test(PARALLEL_LEVEL ${nproc})

      - name: CDash -- Submit
        if: always()
        shell: ctest --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(APPEND)
          set(CTEST_NOTES_FILES "$ENV{GITHUB_WORKSPACE}/clang_version.txt")
          ctest_submit()
