name: FreeBSD
on:
  pull_request:
    paths:
      - '.github/actions/build-depends/action.yml'
      - '.github/workflows/freebsd.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  # See https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories.
  CI_NCPU: 4

jobs:
  freebsd-syslibs:
    name: 'FreeBSD ${{ matrix.release }}: system libs, no GUI'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: freebsd {0}
    strategy: &RELEASE_MATRIX
      fail-fast: false
      matrix:
        # Test all supported releases.
        # See https://www.freebsd.org/releases/.
        include:
          - release: '14.3'
          - release: '15.0'
            # A workaround for https://github.com/bitcoin/bitcoin/pull/34093.
            cxxflags: '-DAPPEND_CXXFLAGS="-Wno-error=sign-compare"'

    steps:
      - &CHECKOUT_BITCOIN_CORE
        name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: maflcko/bitcoin-core
          ref: 2602-test-del

      - &CLEAR_STORAGE_SPACE
        name: Clear unnecessary files on bloated GHA VM
        uses: bitcoin/bitcoin/.github/actions/clear-files@master

      - name: Start FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.release }}
          prepare: pkg install -y curl cmake-core ninja git pkgconf boost-libs libevent sqlite3 capnproto libzmq4 python3 net/py-pyzmq databases/py-sqlite3
          run: git config --global --add safe.directory ${{ github.workspace }}
          sync: 'rsync'
          copyback: false

      - name: Generate buildsystem
        run: |
          cd ${{ github.workspace }}
          cmake -B build -G "Ninja" \
            -DWITH_ZMQ=ON \
            -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON \
            ${{ matrix.cxxflags }} \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - &BUILD
        name: Build
        run: |
          cd ${{ github.workspace }}
          cmake --build build

      - &CHECK_BITCOIND
        name: Check 'bitcoind' executable
        run: |
          set -e
          cd ${{ github.workspace }}
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          ldd build/bin/bitcoind
          build/bin/bitcoind -version

      - &RUN_TEST_SUITE
        name: Run test suite
        run: |
          set -e
          cd ${{ github.workspace }}
          export DIR_UNIT_TEST_DATA="${{ github.workspace }}/qa-assets/unit_test_data"
          mkdir -p ${DIR_UNIT_TEST_DATA}
          curl --location --fail --output "${DIR_UNIT_TEST_DATA}/script_assets_test.json" https://github.com/bitcoin-core/qa-assets/raw/main/unit_test_data/script_assets_test.json
          ctest --test-dir build -j ${{ env.CI_NCPU }} --output-on-failure

      - &RUN_FUNCTIONAL_TESTS
        name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        run: |
          cd ${{ github.workspace }}
          build/test/functional/test_runner.py -j $((${{ env.CI_NCPU }} * 2)) --combinedlogslen=99999999 \
            --extended \
            `# See https://github.com/bitcoin/bitcoin/issues/33128.` \
            --exclude feature_reindex_init \
            --timeout-factor=8

  freebsd-depends:
    name: 'FreeBSD ${{ matrix.release }}: depends'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: freebsd {0}
    strategy: *RELEASE_MATRIX

    steps:
      - *CHECKOUT_BITCOIN_CORE
      - *CLEAR_STORAGE_SPACE

      - name: Start FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.release }}
          prepare: pkg install -y bash curl gmake cmake-core ninja git pkgconf bison python3 net/py-pyzmq databases/py-sqlite3
          run: git config --global --add safe.directory ${{ github.workspace }}
          sync: 'rsync'
          copyback: false

      - name: Checkout helper actions
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/actions/build-depends
          path: ci/nightly

      - name: Build depends
        uses: ./ci/nightly/.github/actions/build-depends
        with:
          vm: freebsd
          # TODO: Fix a linking error.
          options: "NO_QT=1"
          cache-tag: freebsd-${{ matrix.release }}

      - name: Generate buildsystem
        run: |
          cd ${{ github.workspace }}
          cmake -B build -G "Ninja" \
            --toolchain depends/$(depends/config.sub $(depends/config.guess))/toolchain.cmake \
            -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON \
            `# TODO: Reenable GUI tests.` \
            -DBUILD_GUI_TESTS=OFF \
            ${{ matrix.cxxflags }} \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - *BUILD
      - *CHECK_BITCOIND
      - *RUN_TEST_SUITE
      - *RUN_FUNCTIONAL_TESTS
