name: NetBSD
on:
  pull_request:
    paths:
      - '.github/actions/build-depends/action.yml'
      - '.github/workflows/netbsd.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  # See https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories.
  CI_NCPU: 4

jobs:
  netbsd-syslibs:
    name: 'NetBSD ${{ matrix.release }}: system libs, no GUI'
    runs-on: ubuntu-latest
    env:
      PACKAGES: 'boost libevent sqlite3 zeromq'
    defaults:
      run:
        shell: netbsd {0}
    strategy: &RELEASE_MATRIX
      fail-fast: false
      matrix:
        # Test all supported releases.
        # See https://www.netbsd.org/releases/.
        include:
          - release: '9.4'
            capnproto-cppflags: '-DKJ_USE_KQUEUE=0'
            zeromq-cppflags: '-DZMQ_NETBSD_KEVENT_UDATA_INTPTR_T=1'
            packages: 'mozilla-rootcerts-openssl'
          - release: '10.1'

    steps:
      - &CHECKOUT_BITCOIN_CORE
        name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: maflcko/bitcoin-core
          ref: 2602-test-del

      - &START_VM
        name: Start NetBSD VM
        uses: vmactions/netbsd-vm@v1
        with:
          release: ${{ matrix.release }}
          mem: 12288
          prepare: |
            pkg_info > packages_before
            pkg_add -u cmake curl gcc14 git-base ninja-build pkgconf py313-zmq python313 ${{ matrix.packages }} ${{ env.PACKAGES }}
            pkg_info > packages_after
            diff -w packages_before packages_after | grep '^>'
          sync: 'rsync'
          copyback: false

      # The preinstalled `devel/capnproto` package is broken.
      # See https://github.com/bitcoin-core/libmultiprocess/pull/196.
      - name: Build Cap'n Proto
        run: |
          set -e
          pkg_admin -K /usr/pkg/pkgdb fetch-pkg-vulnerabilities
          pkg_add -u digest libtool-base mktools cwrappers
          cd /usr
          cvs -danoncvs@anoncvs.NetBSD.org:/cvsroot checkout -P \
            pkgsrc/devel/capnproto \
            pkgsrc/devel/libtool-base \
            pkgsrc/devel/pkgconf \
            pkgsrc/devel/zlib \
            pkgsrc/lang/gcc15 \
            pkgsrc/mk \
            pkgsrc/pkgtools \
            pkgsrc/security/openssl \
            pkgsrc/sysutils/install-sh/files
          cd /usr/pkgsrc/devel/capnproto
          unset PKG_PATH
          make CPPFLAGS="-DKJ_NO_EXCEPTIONS=0 ${{ matrix.capnproto-cppflags }}" install

      - name: Generate buildsystem
        run: |
          cd ${{ github.workspace }}
          cmake -B build -G "Ninja" \
            -DCMAKE_C_COMPILER="/usr/pkg/gcc14/bin/gcc" -DCMAKE_CXX_COMPILER="/usr/pkg/gcc14/bin/g++" \
            -DWITH_ZMQ=ON \
            -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - &BUILD
        name: Build
        run: |
          cd ${{ github.workspace }}
          cmake --build build

      - &CHECK_BITCOIND
        name: Check 'bitcoind' executable
        run: |
          set -e
          cd ${{ github.workspace }}
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          ldd build/bin/bitcoind
          build/bin/bitcoind -version

      - &RUN_TEST_SUITE
        name: Run test suite
        run: |
          set -e
          cd ${{ github.workspace }}
          export DIR_UNIT_TEST_DATA="${{ github.workspace }}/qa-assets/unit_test_data"
          mkdir -p ${DIR_UNIT_TEST_DATA}
          curl --location --fail --output "${DIR_UNIT_TEST_DATA}/script_assets_test.json" https://github.com/bitcoin-core/qa-assets/raw/main/unit_test_data/script_assets_test.json
          env TMPDIR="${{ github.workspace }}" ctest --test-dir build -j ${{ env.CI_NCPU }} --output-on-failure

      - &RUN_FUNCTIONAL_TESTS
        name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        run: |
          cd ${{ github.workspace }}
          python3.13 build/test/functional/test_runner.py -j $((${{ env.CI_NCPU }} * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix . \
            --extended \
            `# See https://github.com/bitcoin/bitcoin/issues/33128.` \
            --exclude feature_reindex_init \
            --timeout-factor=8

  netbsd-depends:
    name: 'NetBSD ${{ matrix.release }}: depends'
    runs-on: ubuntu-latest
    env:
      PACKAGES: 'gmake perl'
    defaults:
      run:
        shell: netbsd {0}
    strategy: *RELEASE_MATRIX

    steps:
      - *CHECKOUT_BITCOIN_CORE
      - *START_VM

      - name: Checkout helper actions
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/actions/build-depends
          path: ci/nightly

      - name: Build depends
        uses: ./ci/nightly/.github/actions/build-depends
        with:
          vm: netbsd
          options: >
            build_CC=/usr/pkg/gcc14/bin/gcc
            build_CXX=/usr/pkg/gcc14/bin/g++
            CC=/usr/pkg/gcc14/bin/gcc
            CXX=/usr/pkg/gcc14/bin/g++
            native_capnp_cppflags_netbsd=${{ matrix.capnproto-cppflags }}
            capnp_cppflags_netbsd=${{ matrix.capnproto-cppflags }}
            zeromq_cppflags_netbsd=${{ matrix.zeromq-cppflags }}
          cache-tag: netbsd-${{ matrix.release }}

      - name: Generate buildsystem
        run: |
          cd ${{ github.workspace }}
          cmake -B build -G "Ninja" \
            --toolchain depends/$(depends/config.sub $(depends/config.guess))/toolchain.cmake \
            -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - *BUILD
      - *CHECK_BITCOIND
      - *RUN_TEST_SUITE
      - *RUN_FUNCTIONAL_TESTS
