name: OmniOS
on:
  pull_request:
    paths:
      - '.github/workflows/omnios.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  # See https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories.
  CI_NCPU: 4
  # Using the gcc14 and libevent2 packages requires adjusting
  # search directories for the runtime linker
  LD_LIBRARY_PATH: '/opt/gcc-14/lib/amd64:/usr/gnu/lib/amd64'

jobs:
  omnios:
    name: 'OmniOS: system libs, no GUI'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: omnios {0}

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: maflcko/bitcoin-core
          ref: 2602-test-del

      - name: Start OmniOS VM
        uses: vmactions/omnios-vm@v1
        with:
          mem: 12288
          envs: 'LD_LIBRARY_PATH'
          prepare: |
            set -e
            pkg list -H -o name,publisher,version > packages_before
            pkg install cmake ninja git gcc14 pkg-config sqlite-3 python-313
            pkg set-publisher -g https://sfe.opencsw.org/localhostomnios localhostomnios
            pkg install libevent2
            pkg list -H -o name,publisher,version > packages_after
            diff -w packages_before packages_after | grep '^>'
          run: git config --global --add safe.directory ${{ github.workspace }}
          sync: 'rsync'
          copyback: false

      - name: Build Boost
        run: |
          set -e
          curl --location --fail --output boost-1.90.0-cmake.tar.xz https://github.com/boostorg/boost/releases/download/boost-1.90.0/boost-1.90.0-cmake.tar.xz
          tar xf boost-1.90.0-cmake.tar.xz
          cmake -S boost-1.90.0 -B build-boost \
            -DBOOST_INCLUDE_LIBRARIES="multi_index;signals2;test" \
            -DBOOST_TEST_HEADERS_ONLY=ON \
            -DBOOST_ENABLE_MPI=OFF \
            -DBOOST_ENABLE_PYTHON=OFF \
            -DBOOST_INSTALL_LAYOUT=system \
            -DBUILD_TESTING=OFF \
            -DCMAKE_DISABLE_FIND_PACKAGE_ICU=ON
          cmake --install build-boost

      - name: Generate buildsystem
        run: |
          cd ${{ github.workspace }}
          export PKG_CONFIG_PATH="/usr/gnu/lib/amd64/pkgconfig"  # For libevent2 package.
          # Workaround for a bug in the FindThreads module.
          # See https://gitlab.kitware.com/cmake/cmake/-/issues/26063.
          export CXXFLAGS="-pthread"
          cmake -B build -G "Ninja" \
            `# TODO: Build Cap'n Proto from source and reenable IPC.` \
            -DENABLE_IPC=OFF \
            -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - name: Build
        run: |
          cd ${{ github.workspace }}
          cmake --build build

      - name: Check 'bitcoind' executable
        run: |
          set -e
          cd ${{ github.workspace }}
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          ldd build/bin/bitcoind
          build/bin/bitcoind -version

      - name: Run test suite
        run: |
          set -e
          cd ${{ github.workspace }}
          export DIR_UNIT_TEST_DATA="${{ github.workspace }}/qa-assets/unit_test_data"
          mkdir -p ${DIR_UNIT_TEST_DATA}
          curl --location --fail --output "${DIR_UNIT_TEST_DATA}/script_assets_test.json" https://github.com/bitcoin-core/qa-assets/raw/main/unit_test_data/script_assets_test.json
          ctest --test-dir build -j ${{ env.CI_NCPU }} --output-on-failure

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        run: |
          cd ${{ github.workspace }}
          build/test/functional/test_runner.py -j $((${{ env.CI_NCPU }} * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix . \
            --extended \
            `# See https://github.com/bitcoin/bitcoin/issues/33128.` \
            --exclude feature_reindex_init \
            --timeout-factor=8
