name: OpenIndiana
on:
  pull_request:
    paths:
      - '.github/workflows/openindiana.yml'
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name with owner'
        required: true
        default: bitcoin/bitcoin
        type: string
      ref:
        description: 'Repository reference: refs/heads/<branch>, refs/tags/<tag>, refs/pull/<PR>/head or <commit>'
        required: true
        default: refs/heads/master
        type: string
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  # See https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories.
  CI_NCPU: 4
  # Workaround for libstdc++ built with `--enable-clocale=dragonfly`.
  # See https://www.illumos.org/issues/18481.
  LC_ALL: 'C'

jobs:
  openindiana:
    name: 'OpenIndiana: system libs, no GUI'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: openindiana {0}

    steps:
      - name: Annotate with workflow inputs
        if: github.event_name == 'workflow_dispatch'
        env:
          INPUTS_REPOSITORY: ${{ inputs.repository }}
          INPUTS_REF: ${{ inputs.ref }}
        shell: bash
        run: echo "::notice title=inputs::$INPUTS_REPOSITORY $INPUTS_REF"

      - name: Start OpenIndiana VM
        uses: vmactions/openindiana-vm@v1
        with:
          # This release has `metapackages/build-essential` preinstalled.
          release: '202604-build'
          envs: 'LC_ALL'
          # The `pkg install` command often encounters networking issues in the CI
          # environment. To mitigate these, the following steps have been taken:
          # 1. Each package is installed individually.
          # 2. `metapackages/build-essential` (includes git, cmake, gcc-14) and
          #    `runtime/python-314` are already preinstalled on the VM image, so
          #    they are skipped.
          # 3. Installing `system/library/boost` is skipped, as it often takes
          #    more than 60 minutes and causes a job timeout.
          #    See the "Build Boost" step below.
          prepare: |
            set -e
            pkg list > packages_before
            pkg install developer/build/pkgconf
            pkg install library/c++/zeromq
            pkg list > packages_after
            diff -w packages_before packages_after | grep '^>' || true
          sync: no
          disable-cache: true

      - name: Build Boost
        env:
          BOOST_VERSION: '1.92.0'
        run: |
          set -e
          curl --location --fail --output boost.tar.xz https://github.com/boostorg/boost/releases/download/boost-${{ env.BOOST_VERSION }}/boost-${{ env.BOOST_VERSION }}-cmake.tar.xz
          tar xf boost.tar.xz
          cmake -S boost-${{ env.BOOST_VERSION }} -B build-boost \
            -DBOOST_INCLUDE_LIBRARIES="multi_index;test" \
            -DBOOST_TEST_HEADERS_ONLY=ON \
            -DBOOST_ENABLE_MPI=OFF \
            -DBOOST_ENABLE_PYTHON=OFF \
            -DBOOST_INSTALL_LAYOUT=system \
            -DBUILD_TESTING=OFF \
            -DCMAKE_DISABLE_FIND_PACKAGE_ICU=ON
          cmake --install build-boost

      - name: Build Cap'n Proto
        env:
          CAPNPROTO_VERSION: '1.5.0'
        run: |
          set -e
          curl --location --fail --remote-name https://capnproto.org/capnproto-c++-${{ env.CAPNPROTO_VERSION }}.tar.gz
          tar xf capnproto-c++-${{ env.CAPNPROTO_VERSION }}.tar.gz
          cd capnproto-c++-${{ env.CAPNPROTO_VERSION }}
          ./configure --without-fibers
          make -j ${{ env.CI_NCPU }} install

      - name: Fetch source tarball
        run: |
          set -e
          curl --location --fail --output source.tar.gz https://github.com/${{ inputs.repository || 'bitcoin/bitcoin' }}/archive/${{ inputs.ref || 'refs/heads/master' }}.tar.gz
          mkdir bitcoin
          gtar -xf source.tar.gz -C bitcoin --strip-components=1
          rm -rf source.tar.gz

      - name: Generate buildsystem
        run: |
          # Workaround for a bug in the FindThreads module.
          # See https://gitlab.kitware.com/cmake/cmake/-/issues/26063.
          export CXXFLAGS="-pthread"
          cmake -S bitcoin -B build --preset dev-mode \
            -Wno-error=dev \
            -DBUILD_GUI=OFF \
            -DWITH_USDT=OFF \
            -DCMAKE_PREFIX_PATH=/usr/local \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            `# GCC does not support -pie on OpenIndiana.` \
            `# See https://www.illumos.org/issues/15730.` \
            `# Therefore, CMake's check_pie_supported fails and` \
            `# enforcing -fPIC is necessary for BUILD_SHARED_LIBS=ON.` \
            -DAPPEND_CFLAGS="-fPIC" \
            -DAPPEND_CXXFLAGS="-fPIC"

      - name: Build
        run: |
          cmake --build build -- -j ${{ env.CI_NCPU }}

      - name: Check 'bitcoind' executable
        run: |
          set -e
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          ldd build/bin/bitcoind
          build/bin/bitcoind -version

      - name: Run test suite
        run: |
          set -e
          export DIR_UNIT_TEST_DATA="$(pwd)/qa-assets/unit_test_data"
          mkdir -p ${DIR_UNIT_TEST_DATA}
          curl --location --fail --output "${DIR_UNIT_TEST_DATA}/script_assets_test.json" https://github.com/bitcoin-core/qa-assets/raw/main/unit_test_data/script_assets_test.json
          ctest --test-dir build -j ${{ env.CI_NCPU }} --output-on-failure

      - name: Install Python packages for functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        run: |
          set -e
          export PIP_ROOT_USER_ACTION=ignore
          python3.14 -m ensurepip
          python3.14 -m pip install setuptools wheel
          python3.14 -m pip install pyzmq

      - name: Check host disk space
        if: ${{ ! inputs.skip_functional_tests }}
        shell: bash
        run: df -h

      - name: Check VM disk space
        if: ${{ ! inputs.skip_functional_tests }}
        run: df -h "$PWD"

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        run: |
          # Unbuffered stdout prints "Remaining jobs: ..." in order, which
          # helps to identify hung tests.
          export PYTHONUNBUFFERED=1
          python3.14 build/test/functional/test_runner.py -j $((${{ env.CI_NCPU }} * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix "$PWD" \
            --extended \
            `# See https://github.com/bitcoin/bitcoin/issues/33128.` \
            --exclude feature_reindex_init \
            --timeout-factor=8
