name: OpenBSD
on:
  pull_request:
    paths:
      - '.github/actions/build-depends/action.yml'
      - '.github/workflows/openbsd.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  # See https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories.
  CI_NCPU: 4

jobs:
  openbsd-syslibs:
    name: 'OpenBSD ${{ matrix.release }}: system libs, no GUI'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: openbsd {0}
    strategy: &RELEASE_MATRIX
      fail-fast: false
      matrix:
        # Test all supported releases.
        # From https://www.openbsd.org/faq/faq5.html:
        # > Only the two most recent OpenBSD releases receive
        # > security and reliability fixes for the base system.
        # However, Bitcoin Core requires OpenBSD 7.8 or newer.
        # See https://github.com/bitcoin/bitcoin/pull/34182.
        release: ['7.8']

    steps:
      - &CHECKOUT_BITCOIN_CORE
        name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: maflcko/bitcoin-core
          ref: 2602-test-del

      - &CLEAR_STORAGE_SPACE
        name: Clear unnecessary files on bloated GHA VM
        uses: bitcoin/bitcoin/.github/actions/clear-files@master

      - name: Start OpenBSD VM
        uses: vmactions/openbsd-vm@v1
        with:
          release: ${{ matrix.release }}
          prepare: pkg_add -v cmake ninja git boost libevent sqlite3 capnproto zeromq python%3 py3-zmq
          run: git config --global --add safe.directory ${{ github.workspace }}
          sync: 'rsync'
          copyback: false

      - name: Generate buildsystem
        run: |
          cd ${{ github.workspace }}
          cmake -B build -G "Ninja" \
            -DWITH_ZMQ=ON \
            -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - &BUILD
        name: Build
        run: |
          cd ${{ github.workspace }}
          cmake --build build

      - &CHECK_BITCOIND
        name: Check 'bitcoind' executable
        run: |
          set -e
          cd ${{ github.workspace }}
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          ldd build/bin/bitcoind
          build/bin/bitcoind -version

      - &RUN_TEST_SUITE
        name: Run test suite
        run: |
          set -e
          cd ${{ github.workspace }}
          export DIR_UNIT_TEST_DATA="${{ github.workspace }}/qa-assets/unit_test_data"
          mkdir -p ${DIR_UNIT_TEST_DATA}
          curl --location --fail --output "${DIR_UNIT_TEST_DATA}/script_assets_test.json" https://github.com/bitcoin-core/qa-assets/raw/main/unit_test_data/script_assets_test.json
          ctest --test-dir build -j ${{ env.CI_NCPU }} --output-on-failure

      - &RUN_FUNCTIONAL_TESTS
        name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        run: |
          cd ${{ github.workspace }}
          ulimit -n 1024
          build/test/functional/test_runner.py -j $((${{ env.CI_NCPU }} * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix . \
            --extended \
            `# See https://github.com/bitcoin/bitcoin/issues/33128.` \
            --exclude feature_reindex_init \
            `# interface_rest intermittently hangs since 2025-10-23. Running separately in the next command.` \
            --exclude interface_rest \
            --timeout-factor=8
          build/test/functional/test_runner.py interface_rest --combinedlogslen=99999999 \
            --tmpdirprefix . \
            --timeout-factor=8

  openbsd-depends:
    name: 'OpenBSD ${{ matrix.release }}: depends'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: openbsd {0}
    strategy: *RELEASE_MATRIX

    steps:
      - *CHECKOUT_BITCOIN_CORE
      - *CLEAR_STORAGE_SPACE

      - name: Start OpenBSD VM
        uses: vmactions/openbsd-vm@v1
        with:
          release: ${{ matrix.release }}
          prepare: pkg_add -v bash curl gmake gtar-- cmake ninja git python%3 py3-zmq
          run: git config --global --add safe.directory ${{ github.workspace }}
          sync: 'rsync'
          copyback: false

      - name: Checkout helper actions
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/actions/build-depends
          path: ci/nightly

      - name: Build depends
        uses: ./ci/nightly/.github/actions/build-depends
        with:
          vm: openbsd
          cache-tag: openbsd-${{ matrix.release }}

      - name: Generate buildsystem
        run: |
          cd ${{ github.workspace }}
          cmake -B build -G "Ninja" \
            --toolchain depends/$(depends/config.sub $(depends/config.guess))/toolchain.cmake \
            -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - *BUILD
      - *CHECK_BITCOIND
      - *RUN_TEST_SUITE
      - *RUN_FUNCTIONAL_TESTS
