name: Windows, GCC, UCRT
on:
  pull_request:
    paths:
      - '.github/workflows/windows-gcc-ucrt.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  CI_HOST: x86_64-w64-mingw32ucrt

jobs:
  windows-cross:
    name: 'Windows, cross-build only, UCRT: no GUI'
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: maflcko/bitcoin-core
          ref: 2602-test-del

      - name: Install dependencies
        run: |
          dnf install -y cmake make patch ucrt64-gcc-c++ which gawk gcc

      - name: Build depends
        run: |
          gmake -C depends -j $(nproc) HOST=${{ env.CI_HOST }} NO_QT=1 LOG=1

      - name: Generate buildsystem
        run: |
          cmake -B build \
            --toolchain depends/${{ env.CI_HOST }}/toolchain.cmake \
            -DREDUCE_EXPORTS=ON \
            -DBUILD_BENCH=ON \
            -DBUILD_FUZZ_BINARY=ON \
            -DAPPEND_CXXFLAGS="-Wno-error=array-bounds \
              `# TODO: Drop -Wno-error=deprecated-declarations once https://github.com/bitcoin/bitcoin/issues/32361 is fixed.` \
              -Wno-error=deprecated-declarations \
            " \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Upload built executables
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.CI_HOST }}-executables-${{ github.run_id }}
          path: |
            build/bin/*.exe
            build/src/**/*.exe
            build/test/config.ini

  windows-native-test:
    name: 'Windows, test cross-built executables natively'
    runs-on: windows-latest
    needs: windows-cross
    defaults:
      run:
        shell: pwsh -Command "$PSNativeCommandUseErrorActionPreference = $true; $ErrorActionPreference = 'Stop'; & '{0}'"

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: maflcko/bitcoin-core
          ref: 2602-test-del

      - name: Download built executables
        uses: actions/download-artifact@v7
        with:
          name: ${{ env.CI_HOST }}-executables-${{ github.run_id }}

      - name: Configure Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Check 'bitcoind.exe' executable
        run: |
          dumpbin.exe /imports bin\bitcoind.exe | Select-String -Pattern "\S+\.dll" -CaseSensitive:$false
          bin\bitcoind.exe -version

      - name: Run unit tests
        run: |
          bin\test_bitcoin.exe -l test_suite
          src\secp256k1\bin\exhaustive_tests.exe
          src\secp256k1\bin\noverify_tests.exe
          src\secp256k1\bin\tests.exe
          src\univalue\object.exe
          src\univalue\unitester.exe

      - name: Adjust paths in test\config.ini
        run: |
          (Get-Content "test\config.ini") -replace '(?<=^SRCDIR=).*', '${{ github.workspace }}' -replace '(?<=^BUILDDIR=).*', '${{ github.workspace }}' -replace '(?<=^RPCAUTH=).*', '${{ github.workspace }}\share\rpcauth\rpcauth.py' | Set-Content "test\config.ini"
          Get-Content "test\config.ini"

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        shell: bash
        env:
          PYTHONUTF8: 1
        run: |
          py -3 -m pip install pyzmq
          py -3 test/functional/test_runner.py -j $(($NUMBER_OF_PROCESSORS * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix "$RUNNER_TEMP" \
            --extended \
            `# See https://github.com/bitcoin/bitcoin/issues/31409.` \
            --exclude wallet_multiwallet \
            --timeout-factor=40
