name: Windows, LLVM, arm64
on:
  pull_request:
    paths:
      - '.github/workflows/windows-llvm-arm64.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  CI_LLVM_MINGW_URL: https://github.com/mstorsjo/llvm-mingw/releases/download/20260224/llvm-mingw-20260224-ucrt-ubuntu-22.04-x86_64.tar.xz
  CI_LLVM_MINGW_HASH: b89daa0c8eb79e7c8e887fd2ab2b89f99e82c3f1dedab0d2efaa1563a43ad534
  CI_HOST: aarch64-w64-mingw32

jobs:
  windows-aarch64-cross:
    name: 'Windows ARM64, cross-build only, LLVM: no GUI'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: maflcko/bitcoin-core
          ref: 2602-test-del

      - name: Install LLVM MinGW toolchain
        run: |
          curl -L -o llvm_mingw_toolchain.tar.gz ${{ env.CI_LLVM_MINGW_URL }}
          echo "${{ env.CI_LLVM_MINGW_HASH }}  llvm_mingw_toolchain.tar.gz" | sha256sum --check
          mkdir llvm_mingw_toolchain
          tar -xf llvm_mingw_toolchain.tar.gz -C llvm_mingw_toolchain --strip-components=1
          echo "${GITHUB_WORKSPACE}/llvm_mingw_toolchain/bin" >> "$GITHUB_PATH"

      - name: Build depends
        run: |
          gmake -C depends -j $(nproc) HOST=${{ env.CI_HOST }} CC=${{ env.CI_HOST }}-clang CXX=${{ env.CI_HOST }}-clang++ NO_QT=1 NO_ZMQ=1 LOG=1

      - name: Generate buildsystem
        run: |
          cmake -B build \
            --toolchain depends/${{ env.CI_HOST }}/toolchain.cmake \
            -DREDUCE_EXPORTS=ON \
            -DBUILD_BENCH=ON \
            -DBUILD_FUZZ_BINARY=ON \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DAPPEND_CXXFLAGS="-Wno-error=deprecated-declarations -Wno-error=unused-member-function -Wno-error=unused-private-field"

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Upload built executables
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.CI_HOST }}-executables-${{ github.run_id }}
          path: |
            build/bin/*.exe
            build/src/**/*.exe
            build/test/config.ini

  windows-aarch64-native-test:
    name: 'Windows ARM64, test cross-built executables natively'
    runs-on: windows-11-arm
    needs: windows-aarch64-cross
    defaults:
      run:
        shell: pwsh -Command "$PSNativeCommandUseErrorActionPreference = $true; $ErrorActionPreference = 'Stop'; & '{0}'"

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: maflcko/bitcoin-core
          ref: 2602-test-del

      - name: Download built executables
        uses: actions/download-artifact@v7
        with:
          name: ${{ env.CI_HOST }}-executables-${{ github.run_id }}

      - name: Configure Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64

      - name: Check 'bitcoind.exe' executable
        run: |
          dumpbin.exe /imports bin\bitcoind.exe | Select-String -Pattern "\S+\.dll" -CaseSensitive:$false
          bin\bitcoind.exe -version

      - name: Run unit tests
        run: |
          bin\test_bitcoin.exe -l test_suite
          src\secp256k1\bin\exhaustive_tests.exe
          src\secp256k1\bin\noverify_tests.exe
          src\secp256k1\bin\tests.exe
          src\univalue\object.exe
          src\univalue\unitester.exe

      - name: Adjust paths in test\config.ini
        run: |
          (Get-Content "test\config.ini") -replace '(?<=^SRCDIR=).*', '${{ github.workspace }}' -replace '(?<=^BUILDDIR=).*', '${{ github.workspace }}' -replace '(?<=^RPCAUTH=).*', '${{ github.workspace }}\share\rpcauth\rpcauth.py' | Set-Content "test\config.ini"
          Get-Content "test\config.ini"

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        shell: bash
        env:
          PYTHONUTF8: 1
        run: |
          py -3 -m pip install pyzmq
          py -3 test/functional/test_runner.py -j $(($NUMBER_OF_PROCESSORS * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix "$RUNNER_TEMP" \
            --extended \
            `# See https://github.com/bitcoin/bitcoin/issues/31409.` \
            --exclude wallet_multiwallet \
            --timeout-factor=40
