name: Windows, LLVM, x86_64
on:
  pull_request:
    paths:
      - '.github/workflows/windows-llvm-x86_64.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  CI_LLVM_MINGW_URL: https://github.com/mstorsjo/llvm-mingw/releases/download/20260922/llvm-mingw-20260922-ucrt-ubuntu-22.04-x86_64.tar.xz
  CI_LLVM_MINGW_HASH: bb7bb7654b33d5aa8712acb837c963b2e0c56352560c76105270a3268c665c21
  CI_HOST: x86_64-w64-mingw32

jobs:
  windows-x86_64-cross:
    name: 'Windows x86-64, cross-build only, LLVM: no GUI'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v7
        with:
          repository: bitcoin/bitcoin

      - name: Install LLVM MinGW toolchain
        run: |
          curl -L -o llvm_mingw_toolchain.tar.gz ${{ env.CI_LLVM_MINGW_URL }}
          echo "${{ env.CI_LLVM_MINGW_HASH }}  llvm_mingw_toolchain.tar.gz" | sha256sum --check
          mkdir llvm_mingw_toolchain
          tar -xf llvm_mingw_toolchain.tar.gz -C llvm_mingw_toolchain --strip-components=1
          echo "${GITHUB_WORKSPACE}/llvm_mingw_toolchain/bin" >> "$GITHUB_PATH"

      - name: Build depends
        run: |
          gmake -C depends -j $(nproc) HOST=${{ env.CI_HOST }} CC=${{ env.CI_HOST }}-clang CXX=${{ env.CI_HOST }}-clang++ NO_QT=1 LOG=1

      - name: Generate buildsystem
        run: |
          cmake -B build \
            --toolchain depends/${{ env.CI_HOST }}/toolchain.cmake \
            -DREDUCE_EXPORTS=ON \
            -DBUILD_BENCH=ON \
            -DBUILD_FUZZ_BINARY=ON \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DAPPEND_CXXFLAGS="-Wno-error=return-type -Wno-error=conditional-uninitialized"

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Upload built executables
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.CI_HOST }}-executables-${{ github.run_id }}
          path: |
            build/bin/*.exe
            build/src/**/*.exe
            build/test/config.ini

  windows-x86_64-native-test:
    name: 'Windows x86-64, test cross-built executables natively'
    runs-on: windows-2025-vs2026
    needs: windows-x86_64-cross
    defaults:
      run:
        shell: pwsh -Command "$PSNativeCommandUseErrorActionPreference = $true; $ErrorActionPreference = 'Stop'; & '{0}'"

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v7
        with:
          repository: bitcoin/bitcoin

      - name: Download built executables
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.CI_HOST }}-executables-${{ github.run_id }}

      - name: Check 'bitcoind.exe' executable
        # https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-180#developer_command_file_locations
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64 -no_logo
          pwsh.exe -Command "dumpbin.exe /imports bin\bitcoind.exe | Select-String -Pattern '\S+\.dll' -CaseSensitive:$false" || exit 1
          bin\bitcoind.exe -version || exit 1

      - name: Run unit tests
        run: |
          bin\test_bitcoin.exe -l test_suite
          src\secp256k1\bin\exhaustive_tests.exe
          src\secp256k1\bin\noverify_tests.exe
          src\secp256k1\bin\tests.exe
          src\univalue\object.exe
          src\univalue\unitester.exe

      - name: Adjust paths in test\config.ini
        run: |
          (Get-Content "test\config.ini") -replace '(?<=^SRCDIR=).*', '${{ github.workspace }}' -replace '(?<=^BUILDDIR=).*', '${{ github.workspace }}' -replace '(?<=^RPCAUTH=).*', '${{ github.workspace }}\share\rpcauth\rpcauth.py' | Set-Content "test\config.ini"
          Get-Content "test\config.ini"

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        shell: bash
        env:
          PYTHONUTF8: 1
        run: |
          py -3 -m pip install pyzmq
          py -3 test/functional/test_runner.py -j $(($NUMBER_OF_PROCESSORS * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix "$RUNNER_TEMP" \
            --extended \
            --timeout-factor=40
