name: Windows, MSVC
on:
  pull_request:
    paths:
      - '.github/workflows/windows-msvc.yml'
  workflow_dispatch:
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  windows-native:
    name: 'Windows, MSVC, Debug'
    runs-on: windows-2025-vs2026
    defaults:
      run:
        shell: pwsh -Command "$PSNativeCommandUseErrorActionPreference = $true; $ErrorActionPreference = 'Stop'; & '{0}'"

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: maflcko/bitcoin-core
          ref: 2602-test-del

      - name: Configure Developer Command Prompt for Microsoft Visual C++
        # Using microsoft/setup-msbuild is not enough.
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Get tool information
        run: |
          cmake -version | Tee-Object -FilePath "cmake_version"
          Write-Output "---"
          msbuild -version | Tee-Object -FilePath "msbuild_version"
          $env:VCToolsVersion | Tee-Object -FilePath "toolset_version"
          py -3 --version
          Write-Host "PowerShell version $($PSVersionTable.PSVersion.ToString())"

      - name: Generate buildsystem
        run: |
          cmake -B build --preset vs2026 -DBUILD_UTIL_CHAINSTATE=ON -DBUILD_BENCH=ON -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - name: Build
        working-directory: build
        run: |
          cmake --build . -j $env:NUMBER_OF_PROCESSORS --config Debug

      - name: Run test suite
        working-directory: build
        run: |
          ctest -j $env:NUMBER_OF_PROCESSORS --output-on-failure -C Debug
