name: Windows, clang-cl, arm64
on:
  pull_request:
    paths:
      - '.github/workflows/windows-clang-cl-arm64.yml'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean
  workflow_run:
    workflows: ["Manager"]
    types: [requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  windows-native:
    name: 'Windows ARM64, clang-cl'
    runs-on: windows-11-vs2026-arm
    defaults:
      run:
        shell: pwsh -Command "$PSNativeCommandUseErrorActionPreference = $true; $ErrorActionPreference = 'Stop'; & '{0}'"

    steps:
      - name: Install dependencies
        run: |
          Add-Content -Path "$env:VCPKG_INSTALLATION_ROOT\triplets\arm64-windows.cmake" -Value "set(VCPKG_BUILD_TYPE release)"
          vcpkg install boost-multi-index boost-test sqlite3[core] zeromq qtbase[core,gui,network,png,testlib,widgets] qttools libqrencode

      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v7
        with:
          repository: bitcoin/bitcoin
          ref: refs/pull/31507/merge
          fetch-depth: 2

      - name: Get master branch commit hash
        id: master_commit
        run: |
          $commit = git rev-parse HEAD~1
          "commit=$commit" >> $env:GITHUB_OUTPUT

      - name: Generate CTest configuration
        run: |
          $config = @'
          set(CTEST_SITE "${{ github.repository }}")
          set(CTEST_BUILD_NAME "Windows ARM64, clang-cl")
          set(CTEST_SOURCE_DIRECTORY "$ENV{GITHUB_WORKSPACE}")
          set(CTEST_BINARY_DIRECTORY "${CTEST_SOURCE_DIRECTORY}/build")
          set(CTEST_CMAKE_GENERATOR "Visual Studio 18 2026")
          '@
          Set-Content -Path "ctest_config.cmake" -Value $config -Encoding utf8

      - name: CDash -- Start & Update
        shell: ctest --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(${{ case(github.event_name == 'workflow_run', 'Nightly', format('Experimental GROUP {0}', github.event_name)) }})
          find_program(CTEST_GIT_COMMAND git REQUIRED)
          set(CTEST_UPDATE_VERSION_OVERRIDE "${{ steps.master_commit.outputs.commit }}")
          ctest_update()

      - name: CDash -- Configure
        shell: ctest --build-config Release --extra-verbose --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          set(ENV{CXXFLAGS} "-Wno-error=return-type -Wno-error=conditional-uninitialized")
          set(configure_opts
            "-T ClangCL"
            "--preset dev-mode"
            "-DWITH_USDT=OFF"
            "--toolchain $ENV{VCPKG_INSTALLATION_ROOT}\\scripts\\buildsystems\\vcpkg.cmake"
            "-DVCPKG_MANIFEST_MODE=OFF"
            "-DVCPKG_TARGET_TRIPLET=arm64-windows"
            "-DCMAKE_COMPILE_WARNING_AS_ERROR=ON"
          )
          ctest_start(APPEND)
          ctest_configure(OPTIONS "${configure_opts}")

      - name: CDash -- Build
        shell: ctest --build-config Release --extra-verbose --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(APPEND)
          ctest_build(PARALLEL_LEVEL $ENV{NUMBER_OF_PROCESSORS})

      - name: CDash -- Test
        shell: ctest --build-config Release --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(APPEND)
          ctest_test(PARALLEL_LEVEL $ENV{NUMBER_OF_PROCESSORS})

      - name: CDash -- Submit
        if: always()
        shell: ctest --script {0}
        run: |
          include("$ENV{GITHUB_WORKSPACE}/ctest_config.cmake")
          ctest_start(APPEND)
          ctest_submit()

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        working-directory: build
        env:
          PYTHONUTF8: 1
          BITCOIN_BIN: '${{ github.workspace }}\build\bin\Release\bitcoin.exe'
          BITCOIND: '${{ github.workspace }}\build\bin\Release\bitcoind.exe'
          BITCOINCLI: '${{ github.workspace }}\build\bin\Release\bitcoin-cli.exe'
          BITCOIN_BENCH: '${{ github.workspace }}\build\bin\Release\bench_bitcoin.exe'
          BITCOINTX: '${{ github.workspace }}\build\bin\Release\bitcoin-tx.exe'
          BITCOINUTIL: '${{ github.workspace }}\build\bin\Release\bitcoin-util.exe'
          BITCOINWALLET: '${{ github.workspace }}\build\bin\Release\bitcoin-wallet.exe'
          BITCOINCHAINSTATE: '${{ github.workspace }}\build\bin\Release\bitcoin-chainstate.exe'
          TEST_RUNNER_EXTRA: ${{ github.event_name != 'pull_request' && '--extended' || '' }}
        shell: bash
        run: |
          py -3 -m pip install pyzmq
          py -3 test/functional/test_runner.py -j $(($NUMBER_OF_PROCESSORS * 2)) --combinedlogslen=99999999 \
            --tmpdirprefix "$RUNNER_TEMP" \
            --extended \
            --timeout-factor=40
